### ISSUE TITLE
Build error using shake

### ISSUE THREAD

**Issue by He-Ro** [moosotc/llpp#70]
Using the instructions from `BUILDING` on the current head 5987c32d680da981f9e998f2dd5c74ccf104a1a0:
```
Hard way:
  llpp% shake -j0 [build/llpp.native]
or
  llpp% runghc Shakefile.hs -j0 [build/llpp.native]
```
I get the following error:
```
# git (for OracleQ (GitDescribeOracle ()))
# ocamlc.opt (for build/link.o)
# ocamlc.opt (for build/main.cmx)
# ocamlc.opt (for build/config.cmx)
# ocamlc.opt (for build/wsi/x11/wsi.cmx)
# ocamlopt.opt (for build/wsi/x11/wsi.cmx)
In file included from link.c:72:
In file included from mupdf/include/mupdf/fitz.h:25:
mupdf/include/mupdf/fitz/stream.h:418:6: error: variable 'c' may be uninitialized when used here [-Werror,-Wconditional-uninitialized]
        if (c == EOF)
            ^
mupdf/include/mupdf/fitz/stream.h:398:7: note: initialize the variable 'c' to silence this warning
        int c;
             ^
              = 0
1 error generated.
Error when running Shake build system:
* build/llpp.native
* build/link.o
user error (Development.Shake.cmd, system command failed
Command: ocamlc.opt -cc clang -ccopt '-I mupdf/include -I mupdf/thirdparty/freetype/include -Wextra -D_GNU_SOURCE -O2 -g -std=c99 -Wall -Werror -pedantic-errors -Wunused-parameter -Wsign-compare -Wshadow -MMD -MF build/link.d -o build/link.o' -c link.c
Exit code: 2
Stderr:
In file included from link.c:72:
In file included from mupdf/include/mupdf/fitz.h:25:
mupdf/include/mupdf/fitz/stream.h:418:6: error: variable 'c' may be uninitialized when used here [-Werror,-Wconditional-uninitialized]
        if (c == EOF)
            ^
mupdf/include/mupdf/fitz/stream.h:398:7: note: initialize the variable 'c' to silence this warning
        int c;
             ^
              = 0
1 error generated.
)
```

I installed clang, because the first error I got, was that this was not installed, but after that the above errors occured.

Some information about my system:
```
$ clang --version
clang version 5.0.1 (tags/RELEASE_501/final)                            
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

$ shake -v
Shake build system, version 0.16.2

$ghc -V
The Glorious Glasgow Haskell Compilation System, version 8.2.2

$ ocalmc -v
The OCaml compiler, version 4.06.0                                      
Standard library directory: /usr/lib/ocaml

$ ocamlopt -v
The OCaml native-code compiler, version 4.06.0                          
Standard library directory: /usr/lib/ocaml

$ uname -a
Linux archy 4.15.3-2-ARCH #1 SMP PREEMPT Thu Feb 15 00:13:49 UTC 2018 x86_64 GNU/Linux
```
Please let me know if you need any further information.

**Comment by moosotc** [comment]
He-Ro <notifications@github.com> writes:

> Using the instructions from `BUILDING` on the current head 5987c32d680da981f9e998f2dd5c74ccf104a1a0:
> ```
> Hard way:
>   llpp% shake -j0 [build/llpp.native]
> or
>   llpp% runghc Shakefile.hs -j0 [build/llpp.native]
> ```
> I get the following error:

[..snip..]

> Please let me know if you need any further information.

sha id of mupdf.

Thanks for trying to build it both ways btw.

-- 
mailto:moosotc@gmail.com

**Comment by He-Ro** [comment]
I used the commit, that is referenced in BUILDING: `a2a4ad9dceef9610ddc98b2eadb46c3f377516d1`.
I also did `git submodule --update` after checking out that revision. After that I build the libs. Essentially I just copied the commands from BUILDING :wink: 
The error persists, even with your newest commit. (I had to download clang, otherwise shake did not work at all).

**Comment by moosotc** [comment]
He-Ro <notifications@github.com> writes:

> I used the commit, that is referenced in BUILDING:
> `a2a4ad9dceef9610ddc98b2eadb46c3f377516d1`.
> I also did `git submodule --update` after checking out that
> revision. After that I build the libs. Essentially I just copied the
> commands from BUILDING :wink:
> The error persists, even with your newest commit. (I had to download
> clang, otherwise shake did not work at all).

Things should work now (both Shake and shell)

I should ponder how to coerce Shake into using clang conditionally
(AFAIK only 2 people (who aren't me) used shake way ever, you are the
the second one)

-- 
mailto:moosotc@gmail.com

**Comment by He-Ro** [comment]
So it is still giving me the same error about the uninitialized variable in the mupdf include. For me it is not that important. I only tried the shake way, because the `build.sh` way did not work.
But now that `build.sh` is working, I am happy. I will leave the ticket open, because it still does not build for me with shake. If you need further information, please ask me.

**Comment by moosotc** [comment]
He-Ro <notifications@github.com> writes:

> So it is still giving me the same error about the uninitialized
> variable in the mupdf include. For me it is not that important. I only
> tried the shake way, because the `build.sh` way did not work.
> But now that `build.sh` is working, I am happy. I will leave the
> ticket open, because it still does not build for me with shake. If you
> need further information, please ask me.

This one?
'''
In file included from link.c:72:
In file included from mupdf/include/mupdf/fitz.h:25:
mupdf/include/mupdf/fitz/stream.h:418:6: error: variable 'c' may be uninitialized when used here [-Werror,-Wconditional-uninitialized]
        if (c == EOF)
            ^
'''

In my llpp/mupdf checkout this is impossible given that line 398 reads:
'''
	int c = EOF;
'''

It builds and works fine with Shake here (in fact I hardly ever use
build.sh)

If you can dig the issue, that'd be great, but I really don't understand
how the warning you get is possible at all, so, sadly, can't provide any
guidance :(

-- 
mailto:moosotc@gmail.com

**Comment by He-Ro** [comment]
Okay, with the latest master version (commit: `02584b4f4f5a7fa3d13bf622beca3ccd4e08b1c6`) of mupdf it also compiles with shake. Updating the commit in BUILDING would help here.

**Comment by moosotc** [comment]
He-Ro <notifications@github.com> writes:

> Okay, with the latest master version (commit:
> `02584b4f4f5a7fa3d13bf622beca3ccd4e08b1c6`) of mupdf it also compiles
> with shake. Updating the commit in BUILDING would help here.

Grr.. I simply forgot to push.. Thanks for heads up.

-- 
mailto:moosotc@gmail.com
